# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/lab7/lab7.cache/wt} [current_project]
set_property parent.project_path {C:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/lab7/lab7.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo {c:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/lab7/lab7.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/BaudRateGenerator.v}
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/ClockedOneShot.v}
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/DebouncerWithoutLatch.v}
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/DelayLoop.v}
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/bbfifo_16x8.v}
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/kcuart_rx.v}
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/kcuart_tx.v}
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/uart_rx.v}
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/uart_tx.v}
  {C:/Users/pakanalk/Downloads/Lab 7 Source Files-20181219/uartTestece530winter2017.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/lab7/lab7.srcs/constrs_1/new/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/lab7/lab7.srcs/constrs_1/new/constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top uartTestece530winter2017 -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uartTestece530winter2017.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uartTestece530winter2017_utilization_synth.rpt -pb uartTestece530winter2017_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
