# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/DPR_ALU/DPR_ALU.srcs/sources_1/ip/prc_0/prc_0.xci
# IP: The module: 'prc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/DPR_ALU/DPR_ALU.srcs/sources_1/ip/prc_0/prc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'prc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/DPR_ALU/DPR_ALU.srcs/sources_1/ip/prc_0/prc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/DPR_ALU/DPR_ALU.srcs/sources_1/ip/prc_0/prc_0.xci
# IP: The module: 'prc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/DPR_ALU/DPR_ALU.srcs/sources_1/ip/prc_0/prc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'prc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/pakanalk/OneDrive - Rose-Hulman Institute of Technology/Class Files/RISCy Expansion/DRIVE/FPGA_Implementation/DPR_ALU/DPR_ALU.srcs/sources_1/ip/prc_0/prc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
